### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ftorto**
I suggest you to create a license for this great project
I propose MIT if you don't care

### CODE REVIEW

**Comment by ftorto** [comment]
@danielguerra69, could you please add a"hacktoberfest-accepted" label to this PR please ?

**Comment by danielguerra69** [comment]
What is a "hacktoberfest-accepted" label and what  is the purpose ?

**Comment by ftorto** [comment]
In short: https://hacktoberfest.digitalocean.com 

You can plant a tree or earn stickers and t-shirt by contributing to other projects marked with either hacktoberfest topic or by labelling a pr with hacktoberfest-accepted
Labeling doesn't have any impact on your project

**Comment by ftorto** [comment]
@danielguerra69 don't you want to tag it ?

**Pull request merged**
